### ISSUE TITLE
App visual change  

### ISSUE THREAD

**Issue by exezbcz** [dotmemoxyz/app#44]
# gm
figma: 
https://www.figma.com/design/ya6y4sqTxpYwXvedBVE0xt/DOTPOAP_landing?node-id=0-1&t=rKnpLn4g5a3oiGBq-11

## Design
![image](https://github.com/user-attachments/assets/cd02d7e1-3e4f-4e05-8162-d4836fef2526)
- tried maintaining the inputs, copy, etc. 
- some changes were made to the copy 
- ignore "input placeholders please" 
	- keep the ones we use in the app now

### Changes
- image moved under the heading 
- different colors
- border-radius
- changes to navbar 
- main buttons 
- introduced inter typeface as secondary
- headings are now "dark green" not green for legibility 

# .create 
- you can leave the input active state the same as it is, don't have issue with that 
- putting asterisks everywhere as required does not make sense if only one field is optional, lest put optional there 
<img width="532" alt="image" src="https://github.com/user-attachments/assets/4aa09ab5-e921-4f27-aef0-2fcfe346ac77">
<img width="496" alt="image" src="https://github.com/user-attachments/assets/62bb7af8-0661-4d7d-9850-76e788cd3bdf">
this part stays the same 
- renamed "secret" to "claim code" 
- big button

<img width="576" alt="image" src="https://github.com/user-attachments/assets/b0fce802-57f7-4971-8116-ba9eb92ba1d8">

hover is here: 

<img width="216" alt="image" src="https://github.com/user-attachments/assets/268dbcf7-0f36-46cc-aa47-a2512dd8c4f5">

# .Claim
- almost the same, just changing the input component and removing drop shadow
- how this works is grey text

**Comment by brano-hozza** [comment]
@Hladikes already implemented all design changes right?

**Comment by Hladikes** [comment]
@brano-hozza lgtm
